db_types libre
Collecting dbstream==0.1.19

  Downloading dbstream-0.1.19.tar.gz (5.9 kB)

  Preparing metadata (setup.py): started

  Preparing metadata (setup.py): finished with status 'done'

ERROR: Could not find a version that satisfies the requirement db-dtypes==0.3.2 (from versions: 0.0.1a1, 0.0.1a2, 0.1.0, 0.1.1, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1)

ERROR: No matching distribution found for db-dtypes==0.3.2

WARNING: You are using pip version 22.0.3; however, version 23.2.1 is available.

You should consider upgrading via the '/home/adminuser/venv/bin/python -m pip install --upgrade pip' command.

Checking if Streamlit is installed


────────────────────────────────────────────────────────────────────────────────────────


[16:33:43] ❗️ installer returned a non-zero exit code

[16:33:43] ❗️ Error during processing dependencies! Please fix the error and push an update, or try restarting the app.

[16:35:19] ❗️ Streamlit server consistently failed status checks

[16:35:19] ❗️ Please fix the errors, push an update to the git repo, or reboot the app.