mas cambios
ERROR: Cannot install -r /mount/src/datathon_inteligencia_colectiva/Sentimiento/requirements.txt (line 199) and scikit-learn==1.1.3 because these package versions have conflicting dependencies.


The conflict is caused by:

    The user requested scikit-learn==1.1.3

    pingouin 0.5.2 depends on scikit-learn<1.1.0


To fix this you could try to:

1. loosen the range of package versions you've specified

2. remove package versions to allow pip attempt to solve the dependency conflict


ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

WARNING: You are using pip version 22.0.3; however, version 23.2.1 is available.

You should consider upgrading via the '/home/adminuser/venv/bin/python -m pip install --upgrade pip' command.

Checking if Streamlit is installed


────────────────────────────────────────────────────────────────────────────────────────


[15:53:14] ❗️ installer returned a non-zero exit code

[15:53:14] ❗️ Error during processing dependencies! Please fix the error and push an update, or try restarting the app.

[15:54:53] ❗️ Streamlit server consistently failed status checks

[15:54:53] ❗️ Please fix the errors, push an update to the git repo, or reboot the app.