error con pywin32
Collecting python-magic==0.4.27

  Downloading python_magic-0.4.27-py2.py3-none-any.whl (13 kB)

Collecting pytz==2022.7.1

  Downloading pytz-2022.7.1-py2.py3-none-any.whl (499 kB)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 499.4/499.4 KB 262.8 MB/s eta 0:00:00[2023-08-05 15:34:51.902000] 

Collecting pytz-deprecation-shim==0.1.0.post0

  Downloading pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)

ERROR: Could not find a version that satisfies the requirement pywin32==304 (from versions: none)

ERROR: No matching distribution found for pywin32==304

WARNING: You are using pip version 22.0.3; however, version 23.2.1 is available.

You should consider upgrading via the '/home/adminuser/venv/bin/python -m pip install --upgrade pip' command.

Checking if Streamlit is installed


────────────────────────────────────────────────────────────────────────────────────────


[15:34:54] ❗️ installer returned a non-zero exit code

[15:34:54] ❗️ Error during processing dependencies! Please fix the error and push an update, or try restarting the app.

[15:36:27] ❗️ Streamlit server consistently failed status checks

[15:36:27] ❗️ Please fix the errors, push an update to the git repo, or reboot the app.